export const cards = [
  {
    id: 1,
    title: "Hledáme Hudební Duše na Společné Jamování! 🎸🎹",
    description:
      "Jste hudebník nebo milovník hudby? Přijďte k nám do naší hudební komunity, kde se schází lidé se stejným nadšením. Hledáme kytaristy, pianisty, bubeníky a další talentované jedince, kteří chtějí sdílet svou vášeň pro hudbu. Přidejte se k nám a uvidíme, jak nám to ladí 🎶🤘 Kontaktujte nás pro více informací.",
    hashTag: "#JamSession #HudebníKomunita",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card1 Alt",
    date: "2023-11-01",
    phoneNumber: "+420 111 111 111",
    name: "Jan Melodik",
    musicLevel: "Amatér",
    email: "jan.melodik@email.com",
  },
  {
    id: 2,
    title: "Hledám Hudebního Parťáka pro Pohodové Hraní! 🎤🎵",
    description:
      "Jsi zpěvák nebo kytarista? Hledám kamaráda hudebníka, který by chtěl zkusit vytvořit menší kapelu. Rád bych se zaměřil spíše na rock, ale nebráním se i jiným žánrům. Jestli tě tento inzerát zaujal, ozvy se a můžeme to společně rozjet! 🚀🎶",
    hashTag: "#HudebníProjekty #KreativníSpolupráce",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card2 Alt",
    date: "2023-11-22",
    phoneNumber: "+420 111 111 111",
    name: "Eva Harmony",
    musicLevel: "Zábava",
    email: "eva.harmony@email.com",
  },
  {
    id: 3,
    title: "Bubeník Hledá Parťáka pro Groovy Jamování! 🥁🎵",
    description:
      "Jsem bubeník, který miluje groovy rytmy a jamování. Hledám dalšího hudebníka, který by se mnou chtěl tvořit skvělou rytmickou atmosféru. Pokud jsi kytarista, baskytarista nebo jiný hráč na melodický nástroj, dejme tomu společně!",
    hashTag: "#RytmickáDvojice #JamSession",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card3 Alt",
    date: "2023-11-30",
    phoneNumber: "+420 111 111 111",
    name: "Tom Groove",
    musicLevel: "Profi",
    email: "tom.groove@email.com",
  },
  {
    id: 4,
    title: "Spojte Se s Námi - Hledáme Hudební Nadšence! 🎷🎸",
    description:
      "Jsme skupina lidí, kteří si užívají hudbu a hledají nové přátele s podobným zájmem. Bez ohledu na váš hudební nástroj nebo žánr, přidejte se k nám na našich setkáních. Každý týden máme jam session, kde se můžete podělit o svůj talent a poslechnout si ostatní. Přijďte s námi prožít skvělý čas plný hudby a smíchu! 🎶🎉",
    hashTag: "#RytmickáDvojice #JamSession",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card4 Alt",
    date: "2023-10-04",
    phoneNumber: "+420 734 111 111",
    name: "Linda Voice",
    musicLevel: "Zábava",
    email: "linda.voice@email.com",
  },
]

export const guitarAmaters = [
  {
    id: 1,
    title: "Hledám Parťačku na Zpěv a Kytaru 🎤🎸",
    description:
      "Jsem začátečník na kytaře, hledám kamarádku s podobnou vášní. Můžeme zkoušet rock, pop nebo cokoli tě jen napadne. Zkrátka si můžeme jen tak zahrát.",
    hashTag: "#HudebníZačátky #NováKytarováDoba",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card1 Alt",
    date: "2023-09-01",
    phoneNumber: "+420 777 888 999",
    email: "eva.harmony@email.com",
  },
  {
    id: 2,
    title: "Rozjetý Hudební Projekt s Kytarovým Nadšencem! 🎸🔊",
    description:
      "Hledám parťáka na amatérské hraní. Chtěl bych zkusit založit menší kapelu. Ozvi se, ať společně vytvoříme skvělou hudbu!",
    hashTag: "#KytarovéRytmy #HudebníProjekt",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card2 Alt",
    date: "2023-08-15",
    phoneNumber: "+420 606 555 111",
    email: "tom.groove@email.com",
  },
  {
    id: 3,
    title: "Kytarová Nadšenkyně! 🎸",
    description:
      "Jsem začínající kytaristka, hledám parťáka od kterého se mohu učit. Můžeme zkoušet různé styly a najít náš vlastní zvuk. Těším se na spolupráci!",
    hashTag: "#ZpěvnéVýzvy #HudebníSpolupráce",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card3 Alt",
    date: "2023-07-07",
    phoneNumber: "+420 731 222 444",
    email: "linda.voice@email.com",
  },
  {
    id: 4,
    title: "Amatérka Kytaristka s Vlastní Tvořbou 🎸",
    description:
      "Hledám parťáka na pravidelné hraní. Mám pár písniček, které bych chtěla dokončit a zkusit zahrát ve více lidech. Pokud máš zájem tvořit vlastní písničky, neváhej se ozvat.",
    hashTag: "#VlastníSongy #HrajmeSvojePisne",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card4 Alt",
    date: "2023-11-08",
    phoneNumber: "+420 608 999 777",
    email: "petra.beat@email.com",
  },
  {
    id: 5,
    title: "Elektrická Kytara Hledá Doprovod! 🎸⚡",
    description:
      "Jsem nadšený amatér na elektrickou kytaru a hledám parťáka na společné jamování. Máš rád rock a metal? Ideální! Ozvi se, ať spolu roztřepeme reprobedny!",
    hashTag: "#ElektrickáEnergie #HudebníAmatéři",
    imageUrl: "https://picsum.photos/seed/picsum/1000/1000",
    imageAlt: "Card5 Alt",
    date: "2023-11-10",
    phoneNumber: "+420 777 333 555",
    email: "martin.volt@email.com",
  },
]
